name: CD - Deploy to Databricks

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "databricks/**"
      - ".github/workflows/cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Verify Databricks authentication
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks auth describe

      - name: Deploy Databricks scripts
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks workspace import-dir \
            databricks \
            "/Workspace/Users/danharig98@gmail.com/flight_delay_cicd" \
            --overwrite