name: CD - Deploy to Databricks

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "databricks/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@v0.9.0

      - name: Verify Databricks connection
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks current-user me

      - name: Deploy Databricks scripts
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks workspace import-dir \
            databricks \
            /Workspace/Users/email \
            --overwrite